version: "3"

services:
  db:
    build: ./db
    container_name: "fastapi_react_app_db"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: sample_db
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpass
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3308:3308"
    command: --port 3308
    tty: true

  back:
    depends_on:
      - db
    container_name: "fastapi_react_app_back"
    build: ./back
    ports:
      - "8000:8000"
    volumes:
      - ./back/fastapi:/usr/src/server

  front:
    build: ./front
    container_name: "fastapi_react_app_front"
    volumes:
      - ./front:/usr/src/app
#      - /usr/src/app/react-app/node_modules # 追加
    ports:
      - "3000:3000"
    stdin_open: true
